config/routes.rb
Frases::Application.routes.draw do

  resources :sessions
  resources :frases
  resources :comments
  resources :reviews
  resources :notifications
  resources :users
  resources :busquedas
  resources :messages

  root to: "home#index"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'about', to: 'home#about', as: 'about'
  get 'contact', to: 'home#contact', as: 'contact'
  get 'recomendacion', to: 'messages#recomendacion', as: 'recomendacion'
  get 'ranking', to: 'home#ranking', as: 'ranking'
  

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :asunto, :content, :de, :para, :leido
  validates_presence_of :para, :content
  belongs_to :user
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def index
    if logged_in? && !(current_user.tipo.eql? "Bloqueado")
      @messages = Message.where para: current_user.id
      @messages = @messages.sort { |x, y| y.id <=> x.id }
      respond_to do |format|
        format.html
        format.json { render json: @messages }
      end
    else
      if !(logged_in?)
        flash[:error] = "Necesitas Autenticarte para ver los Mensajes!"
        redirect_to login_path
      else
        flash[:error] = "Usuario Bloqueado por Administrador!"
        redirect_to user_path(current_user.id)
      end
    end
  end

  def show
    if logged_in? && ((current_user.id == Message.find(params[:id]).para && !(current_user.tipo.eql? "Bloqueado")) || (current_user.tipo.eql? "Administrador"))
      @message = Message.find(params[:id])
      @mensaje = Message.new
      @message[:leido] = true
      respond_to do |format|
        if @message.update_attributes(params[:message])
          format.html
          format.json { render json: @message }
        end
      end
    else
      if !(logged_in?)
        flash[:error] = "Necesitas Autenticarte para ver los Mensajes!"
        redirect_to login_path
      else
        flash[:error] = "Usuario Bloqueado por Administrador!"
        redirect_to user_path(current_user.id)
      end
    end
  end

  def new
    if logged_in? && !(current_user.tipo.eql? "Bloqueado")
      @message = Message.new
      respond_to do |format|
        format.html
        format.json { render json: @message }
      end
    else
      if !(logged_in?)
        flash[:error] = "Necesitas Autenticarte para enviar Mensajes!"
        redirect_to login_path
      else
        flash[:error] = "Usuario Bloqueado por Administrador!"
        redirect_to user_path(current_user.id)
      end
    end
  end

  def create
    if params[:seguir]
      @message = Message.new(params[:message])
      @message[:para] = params[:para]
      if params[:asunto]
        @message[:asunto] = params[:asunto]
      end
      render action: "new"
    else
      if logged_in? && !(current_user.tipo.eql? "Bloqueado")
        @message = Message.new(params[:message])
        if params[:para]
          x = User.find_by_username(params[:para])
          @message[:asunto] = "Recomendacion"
        else
          x = User.find_by_username(params[:message][:para].downcase)
          @message[:asunto] = "Sin Asunto" unless @message[:asunto]
        end
        if x
          @message[:para] = x.id
          @message[:de] = current_user.id
          @message[:leido] = false
          respond_to do |format|
            if @message.save
              flash[:notice] = params[:para] ? "Recomendacion Enviada!" : "Mensage Enviado!" 
              format.html { redirect_to user_path(@message[:para].to_i)}
              format.json { render json: user_path(@message[:para].to_i), status: :created, location: user_path(params[:para].to_i) }
            else
              format.html { redirect_to user_path(@message[:para].to_i) }
              format.json { render json: @message.errors, status: :unprocessable_entity }
            end
          end
        else
          flash[:error] = 'Usuario no encontrado!'
          render action: "new"
        end
      else
        if !(logged_in?)
          flash[:error] = "Necesitas Autenticarte para hacer esto!"
          redirect_to login_path
        else
          flash[:error] = "Usuario Bloqueado por Administrador!"
          redirect_to user_path(current_user.id)
        end
      end
    end
  end

  def destroy
    @message = Message.find(params[:id]).try(:delete)
    respond_to do |format|
      format.html { redirect_to messages_path }
      format.json { head :no_content }
    end
  end

  def update
  end

  def edit
  end

  def recomendacion
    @message = Message.new
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= simple_form_for @message, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :para, :as => :string, :placeholder => 'Nombre de usuario' %>
  <%= f.input :asunto %>
  <%= f.input :content, :label => 'Mensaje', :as => :text, :input_html => { :rows => 7, :class => 'resizable' }, :placeholder => 'Escribe tu Mensaje' %><br>
  <input class="btn btn-primary" id="button" type="submit" value="Enviar!">
<% end %>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/destroy.html.erb
<h1>Messages#destroy</h1>
<p>Find me in app/views/messages/destroy.html.erb</p>

app/views/messages/edit.html.erb
<h1>Messages#edit</h1>
<p>Find me in app/views/messages/edit.html.erb</p>

app/views/messages/index.html.erb
<div class="inicio">
  <h1 class="titulo">Mensajes</h1><br>
</div>

<div class="tabla">
<%- model_class = Message.new.class -%>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Asunto</th>
      <th>Descripción</th>
      <th>De</th>
      <th>Fecha</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= (message.asunto.eql? "") ? "Sin Asunto" : message.asunto %></td>
        <td><strong><%= (message.content.slice(0..20) + (!message.leido ? " (Nuevo)" : "" )) %></strong></td>
        <td><%= link_to User.find(message.de).username, user_path(message.de) %></td>
        <td><%= message.created_at.strftime("%d-%m-%Y") %></td>
        <td><a class="btn btn-info" id="button" href=<%=message_path(message.id)%>><i class="icon-search icon-white"></i> Ver </a>
          <%= link_to t('.destroy', :default => t("helpers.links.Eliminar")),
                      message_path(message),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Seguro?')),
                      :class => 'btn btn-danger',
                      :id => "button" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<a class="btn btn-inverse" id="button" href=<%=user_path(current_user.id)%>><i class="icon-arrow-left icon-white"></i> Perfil </a>
<a class="btn btn-primary" id="button" href=<%=new_message_path%>> Nuevo Mensaje </a>
<a class="btn btn-primary" id="button" href=<%=new_frase_path%>> Expresarme! </a><br>
<br>
</div>
<div class="final"><br></div>

app/views/messages/new.html.erb
<% if @message.errors.any? %>
<div class="alert alert-error">
  <a class="close" data-dismiss="alert">×</a>
	<% if @message.errors.any? %>
	  <div id="error_explanation">
	      <% @message.errors.full_messages.each do |msg| %>
	        <%= msg %>
	      <% end %>
	  </div>
	<% end %>
</div>
<% end %>
<div class="autent">
	<h1 class="titulo"> Nuevo Mensaje </h1>
	<%= render 'form'%> 
	<a class="btn btn-inverse" id="button" href=<%=messages_path%>><i class="icon-arrow-left icon-white"></i> Mensajes </a>
</div>

app/views/messages/recomendacion.html.erb
<div class="session">
<%= simple_form_for @message do |f| %>
  <div class="field">
    <%= f.input :content, :label => 'Recomendación', :as => :text, :input_html => { :rows => 7, :class => 'resizable' }, :placeholder => 'Escribe tu Recomendación u opinión' %>
    <%= hidden_field_tag(:para, "jamthebest") %>
  </div>

  <input class="btn btn-primary" id="button" type="submit" value="Enviar!">
<% end %>

<a class="btn btn-inverse" id="button" href=<%=messages_path%>><i class="icon-arrow-left icon-white"></i> Mensajes </a>
<a class="btn btn-inverse" id="button" href=<%=root_url%>><i class="icon-home icon-white"></i> Inicio </a>
</div>

<div class="comeface">
	<div class="fb-comments" data-href="https://www.facebook.com/jamthebest221" data-num-posts="3" data-width="450"></div>
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
  	var js, fjs = d.getElementsByTagName(s)[0];
  	if (d.getElementById(id)) return;
  	js = d.createElement(s); js.id = id;
  	js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1";
  	fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
</div><br>

app/views/messages/show.html.erb
<%- model_class = @message.class -%>
<div class="page-header">
  <h1>Mensaje</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:de) %>:</strong></dt>
  <dd><%= link_to User.find(@message.de).username, user_path(@message.de) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:asunto) %>:</strong></dt>
  <dd><%= !(@message.asunto.eql? "") ? @message.asunto : "Sin Asunto" %></dd>
  <dt><strong>Mensaje:</strong></dt>
  <dd><%= @message.content %></dd>
  
</dl>

<div class="form-actions">
  <%= simple_form_for @mensaje do |f| %>
    <%= hidden_field_tag(:seguir, true) %>
    <%= hidden_field_tag(:para, User.find(@message.de).username) %>
    <%= hidden_field_tag(:asunto, "Res: "+ @message.asunto) %>
    <input class="btn btn-primary" id="button" type="submit" value="Responder">
  <% end %>
  <a class="btn btn-inverse" id="button" href=<%=messages_path%>><i class="icon-arrow-left icon-white"></i> Atrás </a>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              message_path(@message),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger',
              :id => "button" %>
</div>

app/views/messages/update.html.erb
<h1>Messages#update</h1>
<p>Find me in app/views/messages/update.html.erb</p>