config/routes.rb
Frases::Application.routes.draw do

  resources :sessions
  resources :frases
  resources :comments
  resources :reviews
  resources :notifications
  resources :users
  resources :busquedas
  resources :messages

  root to: "home#index"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'about', to: 'home#about', as: 'about'
  get 'contact', to: 'home#contact', as: 'contact'
  get 'recomendacion', to: 'messages#recomendacion', as: 'recomendacion'
  get 'ranking', to: 'home#ranking', as: 'ranking'
  

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_attached_file :photo, :styles => { :show => "200x200>", :index => "100x100>", :otro => "300x300>" }, 
										:default_url => "/photos/default.png"
  attr_accessible :photo
  attr_accessible :apellido, :email, :fecha_nac, :nombre, :username, :tipo, :password, :password_confirmation
  validates_uniqueness_of :username, :email
  validates_presence_of :apellido, :email, :fecha_nac, :nombre, :username

  has_many :reviews
  has_many :notifications
  has_many :messages
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if logged_in? && (current_user.tipo.eql? "Administrador")
      @users = User.all
      @users = @users.sort { |x, y| y.id <=> x.id }
      respond_to do |format|
        format.html
        format.json { render json: @users }
      end
    else
      flash[:error] = 'No tienes derechos de Administrador!'
      if !(logged_in?)
        redirect_to login_path
      else
        redirect_to root_url
      end
    end
  end

  def show
    @user = User.find(params[:id])
    @review = Review.new
    @notification = Notification.new
    @message = Message.new
    respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end

  def new
    if !(logged_in?)
      @user = User.new
      respond_to do |format|
        format.html
        format.json { render json: @user }
      end
    else
      flash[:error] = "No puedes crear un usuario cuando estes autenticado!"
      redirect_to users_path
    end
  end

  def create
    if !(logged_in?)
      @user = User.new(params[:user])
      if params[:tipo]
        @user[:tipo] = params[:tipo]
      end
      respond_to do |format|
       if @user.save
          session[:user_id] = @user.id
          format.html { redirect_to @user, notice: 'Usuario Creado!' }
          format.json { render json: @user, status: :created, location: @user }
       else
          format.html { render action: "new" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:error] = "No puedes crear un usuario cuando estes autenticado!"
      redirect_to user_path(@user.id)
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if !(current_user.tipo.eql? "Administrador")
      @user[:tipo] = params[:tipo]
    end
    if (current_user.id == @user.id) || (current_user.tipo.eql? "Administrador")
      respond_to do |format|
        if @user.update_attributes(params[:user])
          format.html { redirect_to @user, notice: 'Usuario Actualizado!' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:error] = "No puedes Modificar este Usuario!"
      redirect_to @user
    end
  end

  def destroy
    if (current_user.id == User.find(params[:id])) || (current_user.tipo.eql? "Administrador")
      @user = User.find(params[:id])
      @user.destroy

      respond_to do |format|
        format.html { redirect_to users_path }
        format.json { head :no_content }
      end
    else
      flash[:error] = "No puedes Eliminar este Usuario!"
      redirect_to @user
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="userform">
<%= simple_form_for(@user) do |f| %>
  <%= f.input :nombre %>
  <%= f.input :apellido %>
  <%= f.input :fecha_nac, :label =>'Fecha de Nacimiento', :as => :date, :start_year => Date.today.year - 100,
          :end_year => Date.today.year, 
          :order => [:day, :month, :year] %>
  <%= f.input :username, :placeholder => 'Nombre para Identificarte'%>
  <%= f.input :email, :placeholder => 'Tu correo electrónico'%>
  <%= f.input :password, :placeholder => 'Contraseña'%>
  <%= f.input :password_confirmation, :placeholder => 'Ingresa la contraseña nuevamente' %>
  <% if logged_in? && (current_user.tipo.eql? "Administrador") %>
    <%= f.input :tipo %>
  <% else %>
    <%= hidden_field_tag(:tipo, "Usuario") %>
  <% end %>
  Foto de Perfil: <%= f.file_field :photo %><br><br>
  <input class="btn btn-primary" id="button" type="submit" value="Listo!">
<% end %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<div class="autent">
	<h1 class="titulo">Editar Usuario</h1>
	<%= render 'form' %>
	<a class="btn btn-info" id="button" href=<%=user_path(@user.id)%>><i class="icon-search icon-white"></i> Mostrar </a>
</div>

app/views/users/index.html.erb
<div class="inicio">
  <h1 class="titulo">Usuarios</h1><br>
</div>

<div class="tabla">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Foto</th>
        <th>Email</th>
        <th>Username</th>
        <th>Nombre</th>
        <th>Tipo</th>
        <th>Creación</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <% @users.each do |user| %>
    <tbody>
      <tr>
        <td><%= user.id %></td>
        <td><%= image_tag user.photo.url(:index) %></td>
        <td><%= user.email %></td>
        <td><%= link_to user.username, user_path(user) %></td>
        <td><%= user.nombre %> <%= user.apellido %></td>
        <td><%= user.tipo %></td>
        <td><%= user.created_at.strftime("%d-%m-%Y") %></td>
        <td><a class="btn btn-success" id="button" href=<%=edit_user_path(user.id)%>><i class="icon-pencil icon-white"></i> Editar </a>
        <td><a class="btn btn-danger" id="button" data-confirm="Are you sure?" data-method="delete" href=<%=user_path(user.id)%>><i class="icon-trash icon-white"></i> Borrar </a></td>
      </tr>
    </tbody>
    <% end %>
  </table>

  <a class="btn btn-inverse" id="button" href=<%=root_url%>><i class="icon-arrow-left icon-white"></i> Inicio </a>
  <a class="btn btn-primary" id="button" href=<%=new_user_path%>> Nuevo Usario </a>
  <br>
</div>
<div class="final"><br></div>

app/views/users/new.html.erb
<div class="autent">
	<h1 class="titulo">Nuevo Usuario</h1>
	<%= render 'form' %>
	Al darle al botón Listo! aceptarás los Términos de <b>JAM-Exprésate</b><br><br>
	<div class="terminos">
		<b>Términos de JAM-Exprésate</b><br>
  	<p>
			<b>JAM-Exprésate</b> es un servicio donde puedes expresar tus sentimientos, tus palabras o frases que quieras compartir. Al ser usuario puedes <b>Expresarte</b>, editar tus <b>Expresiones</b>, eliminarlas, ver todas las Expresiones, buscar una en específico, entre otros. Siempre hay que tener en cuenta <b>EL RESPETO HACIA LOS DEMÁS y principalmente hacia DIOS.</b>
		</p>
		<p>
			Cada usuario puede hacer comentarios sobre las <b>Expresiones</b> de otros usuarios y sobre los usuarios mismos.	Cuando un usuario haya hecho un comentario o compartido una <b>Expresión</b> que sea inadecuado(a) se puede reportar al administrador para que éste lo verifique y lo(a) elimine y tome sanciones sobre dicho usuario.
		</p>
		<p>
			El Administrador puede disponer de tus <b>Expresiones</b> y de tu cuenta al haber un 
			comportamiento inadecuado de tu parte. Tu cuenta puede ser bloqueada por el Administrador
			si este lo considera necesario. <br><br><b>Exprésate XD.</b>
		</p>
  </div>
	<br><a class="btn btn-inverse" id="button" href=<%=root_url%>><i class="icon-home icon-white"></i> Inicio </a>
</div>

app/views/users/show.html.erb
<div class="autent" class="user">
<p class="titulouser">
  <br><strong>Username:</strong>
  <%= @user.username %>
</p>
<div class="foto"><%= image_tag @user.photo.url(:show), :class => "photo" %></div>
<div class="noti">
  <% if logged_in? && current_user.id == @user.id %>
    <a class="btn btn-warning" id="button" href=<%=notifications_path%>><i class="icon-search icon-white"></i> Notificaciones </a>
  <%end%><br><br>
</div>

<% if logged_in? && (current_user.id == @user.id || (current_user.tipo.eql? "Administrador")) %>
<div class="libros">
    <br>
    <a class="btn btn-danger" id="button" data-confirm="Are you sure?" data-method="delete" href=<%=user_path(@user.id)%>><i class="icon-trash icon-white"></i> Borrar Usuario </a>
    <a class="btn btn-success" id="button" href=<%=edit_user_path(@user.id)%>><i class="icon-pencil icon-white"></i> Editar Perfil </a>
    <br><hr>
  <p><h3 id="cont">Mis Expresiones:</h3></p>
  <div class="lista">
    <ol>
      <%(Frase.where user_id: @user.id).each do |frase|%>
        <li><h4><strong><%= link_to "#{frase.descripcion.slice(0..40)}", frase_path(frase.id) %></strong></h4></li><br>
      <% end %>
    </ol>
  </div>
  <br>
</div>
<%end%>
<hr>
<div class="infor">
<% if !current_user || current_user.id != @user.id %></p>
  <p><strong class="datos">Nombre:</strong> <%=@user.nombre%> <%=@user.apellido%></p>
  <p><strong class="datos">Fecha de Nacimiento:</strong> <%=@user.fecha_nac.strftime("%d-%m-%Y")%></p>
  <p><strong class="datos">E-mail:</strong> <%=@user.email%></p>
  <%= simple_form_for @message do |f| %>
    <%= hidden_field_tag(:seguir, true) %>
    <%= hidden_field_tag(:para, @user.username) %>
    <input class="btn btn-primary" id="button" type="submit" value="Enviar Mensaje">
  <% end %>
  <hr>
  <p><h3 id="cont">Expresiones:</h3></p>
  <div class="lista"> 
    <ol>
      <%(Frase.where user_id: @user.id).each do |frase|%>
        <li><h4 class="fracont"><strong><%= link_to "#{frase.descripcion}", frase_path(frase.id) %></strong></h4></li><br>
      <% end %>
    </ol>
  </div><hr>
<% end %>

</div>
<a class="btn btn-inverse" id="button" href=<%=root_url%>><i class="icon-home icon-white"></i> Inicio </a>
<a class="btn btn-primary" id="button" href=<%=new_frase_path%>> Expresarme! </a><br><br>
  <br><%= simple_form_for @review do |f| %>
    <b><%= "Agregue un comentario acerca de este usuario!" %></b>
    <br><br><textarea class="text optional" cols="10" id="comentario_content" name="review[contenido]" rows="4" placeholder="Escribe un comentario..."></textarea><br>
    <%= hidden_field_tag(:perfil, @user.id) %>
    <input class="btn btn-primary" id="button" type="submit" value="Comentar">
  <% end %>

<div class="review">
  <br><h3 id="cont">Comentarios:</h3>
  <%(Review.where perfil: @user.id).sort{|x,y| y.created_at <=> x.created_at}.each do |comment|%>
    <div class="lista">
      <ol id="comment_list">
        <p><h4><%= link_to "#{User.find(comment.user_id).username}", user_path(comment.user_id) %> escribió</h4></p>
        <p><h4><%= comment.contenido %></h4></p>
        <div class="reporte" >
          <%= simple_form_for @notification do |f| %>
            <%= hidden_field_tag(:para, 1) %>
            <%= hidden_field_tag(:tipo, 1) %>
            <%= hidden_field_tag(:contenido, ("Comentario Indevido : " + comment.contenido + "  Usuario: " + User.find(comment.user_id).username + "   De: " + (logged_in? ? (current_user.username) : "Invitado")).to_s) %>
            <input class="btn btn-primary" id="button" type="submit" value="Reportar">
          <% end %>
        </div>
      </ol>
    </div>
  <% end %>
  <br><br>
</div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>