config/routes.rb
Frases::Application.routes.draw do

  resources :sessions
  resources :frases
  resources :comments
  resources :reviews
  resources :notifications
  resources :users
  resources :busquedas
  resources :messages

  root to: "home#index"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'about', to: 'home#about', as: 'about'
  get 'contact', to: 'home#contact', as: 'contact'
  get 'recomendacion', to: 'messages#recomendacion', as: 'recomendacion'
  get 'ranking', to: 'home#ranking', as: 'ranking'
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def ranking
  	@frases = []
  	ban = (Frase.all.size > 10) ? 10 : Frase.all.size
  	x = Frase.all.sort { |x, y| y.likes <=> x.likes }
  	for i in 0..(ban-1)
  		@frases[i] = x[i]
  	end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="principal2">
	
	<div class="texto2">
		<div class="per"><img src="jam.jpg"></div>
	<p><br><br><br>
		Mi nombre es Javier Midence Estudiante de <br>Ingeniería en Sitemas Computacionales en <br>UNITEC Honduras. <br><br>Soy Hondureño, de Tegucigalpa. Este es mi<br> primer proyecto(aparte de los de la clase de<br>Progamación) que realizo personalmente.
	</p>
	</div><br>
	<br><br><br><h1 class="jam">JAM-<br>Exprésate</h1><br><br><br>
	<div class="icono"></div>
	<div class="container" id="content2">
		<a class="btn btn-info" id="button" href=<%=frases_path%>><i class="icon-eye-open"></i> Ver Expresiones </a>
		<a class="btn btn-inverse" id="button" href=<%=root_url%>><i class="icon-home icon-white"></i> Inicio </a>
	</div>
</div>

app/views/home/contact.html.erb
<div class="principal">
	
	<div class="texto2">
	<p><br><br>
		Correo: 
		<ul>
			<li><a href="mailto:javmidence@yahoo.es" TARGET="_new">javmidence@yahoo.es</a></li>
			<li><a href="mailto:javier.midence@unitec.edu" TARGET="_new">javier.midence@unitec.edu</a></li>
		</ul>
		<br>
		Facebook:
		<ul>
			<li><a href="http://www.facebook.com/jamthebest22" target="_new">Javier Midence </a></li>
			<li><a href="http://www.facebook.com/jamthebest221" target="_new">Jam-Exprésate</a></li>
		</ul>
		<br>
	</p><br><br>
	</div><br>
	<h1 class="jam">JAM-<br>Exprésate</h1><br><br><br>
	<div class="icono"></div>
	<div class="container" id="content2">
		<a class="btn btn-info" id="button" href=<%=frases_path%>><i class="icon-eye-open"></i> Ver Expresiones </a>
		<a class="btn btn-inverse" id="button" href=<%=root_url%>><i class="icon-home icon-white"></i> Inicio </a>
	</div>
</div>

app/views/home/index.html.erb
<div class="principal">
	<div class="texto">
	<p>
		<br><br><br><br><br>
		Comparte lo que quieres <br> compartir!!!
		<br><br><br><br><br><br>
	</p>
	</div><br>
	<h1 class="jam">JAM-<br>Exprésate</h1><br><br><br>
	<div class="icono"></div>
	<div class="container" id="content1">
		<a class="btn btn-info" id="button" href=<%=frases_path%>><i class="icon-eye-open"></i> Ver Expresiones </a>
		<a class="btn btn-success" id="button" href=<%=ranking_path%>><i class="icon-star"></i> Ranking </a>
	</div>
</div>
<div class="pie">
	<div class="comeface">
		<div class="fb-comments" data-href="https://www.facebook.com/jamthebest221" data-num-posts="3" data-width="450"></div>
		<div id="fb-root"></div>
		<script>(function(d, s, id) {
	  	var js, fjs = d.getElementsByTagName(s)[0];
	  	if (d.getElementById(id)) return;
	  	js = d.createElement(s); js.id = id;
	  	js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1";
	  	fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>
	</div><br><br><br><br><br><br><br><br>
    <b class="acerca"><%= link_to "Acerca de Mí", about_path %></b>
    <b class="contacto"><%= link_to "Contáctanos", contact_path %></b>
    <b class="contador">
    	<!-- inicio codigo contador --><a href="http://contador-de-visitas.com"><img style="border: 0px solid ; display: inline;" alt="contador de visitas" 
  		src="http://contador-de-visitas.com/hit.php?id=1362923&counter=24"></a>
  <!-- fin codigo contador -->
		<b class="acerca"><%= link_to "Recomendación", recomendacion_path %></b>
</div>

app/views/home/ranking.html.erb
<div class="inicio">
  <h1 class="titulo">Ranking XD</h1><br>
</div>
<div class="tabla">
		<table class="table table-striped">
	    <thead>
	      <tr>
	        <th>Posición</th>
	        <th>Frase</th>
	        <th>Autor</th>
	        <th>Usuario</th>
	        <th>Votos</th>
	      </tr>
	    </thead>
	    <% cont = 1 %>
	    <% @frases.each do |frase| %>
	    <tbody>
	      <tr>
	        <td><%= cont %></td>
	        <td><%= link_to frase.descripcion.slice(0..40) + ((Frase.find(frase.id).descripcion.size > 40) ? "..." : ""), frase_path(frase) %></td>
	        <td><%= frase.autor %></td>
	        <td><%= link_to User.find(frase.user_id).username, user_path(frase.user_id) %></td>
	        <td><%= frase.likes %></td>
	      </tr>
	    </tbody>
	    <% cont += 1%>
	    <% end %>
  	</table>

<br>
<br><a class="btn btn-inverse" id="button" href=<%=root_url%>><i class="icon-home icon-white"></i> Inicio </a>
<a class="btn btn-primary" id="button" href=<%=new_frase_path%>> Expresarme! </a><br>
</div>
<div class="final"><br></div>