config/routes.rb
Frases::Application.routes.draw do

  resources :sessions
  resources :frases
  resources :comments
  resources :reviews
  resources :notifications
  resources :users
  resources :busquedas
  resources :messages

  root to: "home#index"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'about', to: 'home#about', as: 'about'
  get 'contact', to: 'home#contact', as: 'contact'
  get 'recomendacion', to: 'messages#recomendacion', as: 'recomendacion'
  get 'ranking', to: 'home#ranking', as: 'ranking'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JAM-Exprésate</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag "bootstrap/css/bootstrap.css"%>
  <link rel="shortcut icon" href="http://www.iconj.com/ico/m/v/mvxyi0eqxp.ico" type="image/x-icon" />
  <link href='http://fonts.googleapis.com/css?family=Bad+Script' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Bilbo+Swash+Caps' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Berkshire+Swash' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Fredericka+the+Great' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Frijole' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Bad+Script' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Gentium+Basic' rel='stylesheet' type='text/css'>
</head>
<body>
	<div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">JAM-Exprésate</a>
        <div class="nav-collapse">
          <ul class="nav">
            <% if logged_in? %>
            <li><a href=<%=notifications_path %>><i class="icon-globe icon-white"></i> <%=noti.size%></a></li>
            <li><a href=<%=messages_path%>><i class="icon-envelope icon-white"></i> <%=messa.size%></a></li>
            <% end %>
            <li><a href=<%=new_frase_path%> class="move"><marquee onMouseOver="this.stop()" onMouseOut="this.start()" scrolldelay=150 behavior="alternate">Exprésate</marquee></a></li>
          </ul>
          <ul class="nav pull-right" id="bar">
          	<% unless logged_in? %>
  						<li><%= link_to "Nueva Cuenta", signup_path %></li>
  						<li><%= link_to "Autenticar", login_path %></li>
						<% else %>
						  <li><%= link_to current_user.username, user_path(current_user.id) %></li>
						  <li><%= link_to "Salir", logout_path %></li>
						<%end%>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="face">
    <iframe src="//www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fjamthebest221&amp;width=150&amp;height=290&amp;colorscheme=light&amp;show_faces=true&amp;border_color&amp;stream=false&amp;header=true" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:150px; height:290px;" allowTransparency="true"></iframe><br><br>
  </div>

  <div class="container" id="conteni">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <a class="close" data-dismiss="alert">×</a>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:error] %>
      <div class="alert alert-error">
        <a class="close" data-dismiss="alert">×</a>
        <%= flash[:error] %>
      </div>
    <% end %>
    <%= yield %>
  </div>
  <div>
    
    <table  border="0" width="135" height="196" ><tr><td><iframe src="http://www.recursosblog.net/archivos-calendarios/calendario4.html" width="135" height="196" marginwidth="0" marginheight="0" frameborder="no" scrolling=no allowtransparency="true"></iframe></td></tr></table>
    

    <span id="usuarios_activos"><a target="_blank" href="http://www.joseane.com/recursos/usuarios_en_linea.asp">Calcula los usuarios online de tu web o blog</a></span><script type="text/javascript" src="http://usu.joseane.com/usuact.asp?web=631173413300"></script><br>

    <br><a href="/about"><marquee scrollamount="6" scrolldelay=150 scrolldelay="1" direction="left" loop="true">Por Javier Midence</marquee></a>

  </div>
</body>
</html>